Metrics/LineLength:
  Max: 128
Metrics/MethodLength:
  Max: 100
Metrics/ModuleLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/AccessorMethodName:
  Enabled: false
Lint/NestedMethodDefinition:
  Enabled: false
